---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-dev-cluster1
  region: us-west-2
nodeGroups:
  - name: my-dev-workers
    instanceType: t2.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 4